# fly.toml app configuration file generated for dodik-discord-bot on 2026-07-26T16:06:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dodik-discord-bot'
primary_region = 'fra'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
